version: '3.8'

services:
  discovery-service:
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    container_name: discovery-service
    ports:
      - "8761:8761"
    restart: unless-stopped

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.3
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.3
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  postgres-db:
    image: postgres:15-alpine
    container_name: easylink-postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=easylink_user
      - POSTGRES_PASSWORD=easylink_password
      - POSTGRES_DB=easylink_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  mongo-db:
    image: mongo:7.0
    container_name: easylink-mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword

  redis-cache:
    image: redis:7-alpine
    container_name: easylink-redis-cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  easylink-service:
    build:
      context: ./easylink-service
      dockerfile: Dockerfile
    container_name: easylink-service
    ports:
      - "8081:8081"
    depends_on:
      - discovery-service
      - postgres-db
      - kafka
      - redis-cache
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/easylink_db
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      SPRING_DATA_REDIS_HOST: redis-cache
    restart: unless-stopped

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "8083:8083"
    depends_on:
      - discovery-service # Deve esperar o Eureka
      - postgres-db       # Deve esperar o Postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/easylink_db
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
      API_SECURITY_TOKEN_SECRET: ${API_JWT_SECRET_KEY:-meu-secret-super-secreto-para-gerar-tokens-do-easylink}
    restart: unless-stopped

  analytics-service:
    build:
      context: ./analytics-service
      dockerfile: Dockerfile
    container_name: analytics-service
    ports:
      - "8082:8082"
    depends_on:
      - discovery-service # Deve esperar o Eureka
      - kafka             # Deve esperar o Kafka
      - mongo-db          # Deve esperar o MongoDB
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      SPRING_DATA_MONGODB_URI: mongodb://root:rootpassword@mongo-db:27017/analytics_db?authSource=admin
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  mongo_data:
    driver: local
  redis_data:
    driver: local