version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: easylink-postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=easylink_user
      - POSTGRES_PASSWORD=easylink_password
      - POSTGRES_DB=easylink_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local