server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        # Rota 1
        - id: easylink-service-api-route
          uri: lb://easylink-service
          predicates:
            - Path=/api/v1/**
        # Rota 2
        - id: easylink-service-redirect-route
          uri: lb://easylink-service
          predicates:
            - Path=/{shortKey:[a-zA-Z0-9]{8}}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
