global:
  scrape_interval: 15s # Com que frequência coletar métricas.
  evaluation_interval: 15s # Com que frequência avaliar regras.

scrape_configs:
  - job_name: 'easylink-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['easylink-service:8081']

  - job_name: 'user-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['user-service:8083']

  - job_name: 'api-gateway'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: 'analytics-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['analytics-service:8082']

  # Coletar métricas do próprio Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']