CREATE TABLE url_mappings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    short_key VARCHAR(255) NOT NULL,
    original_url VARCHAR(2048) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    owner_username VARCHAR(255) NOT NULL
);

CREATE UNIQUE INDEX idx_unique_short_key ON url_mappings(short_key);