name: EasyLink CI Pipeline

on:
  push:
    branches: [ "main", "develop" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [ 'user-service', 'easylink-service', 'analytics-service', 'api-gateway', 'discovery-service' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Make Maven Wrapper executable
        run: chmod +x ${{ matrix.service }}/mvnw

      - name: Build and Test with Maven
        run: cd ${{ matrix.service }} && ./mvnw clean verify